//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsitePhanPhoiSach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class phieuxuat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public phieuxuat()
        {
            this.ctpxes = new HashSet<ctpx>();
        }
    
        public int idpx { get; set; }
        public Nullable<int> iddl { get; set; }
        public string nguoinhan { get; set; }
        public Nullable<System.DateTime> ngayxuat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ctpx> ctpxes { get; set; }
        public virtual daily daily { get; set; }
    }
}
